# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ansible-galaxy-deploy

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ansible pycodestyle pylint pytest coverage \
            voluptuous pytest-xdist yamllint galaxy-importer
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        ansible-galaxy collection install ansible.netcommon
        mkdir -p ~/.ansible/collections/ansible_collections/qaxi/ciscosmb
        cp -r * ~/.ansible/collections/ansible_collections/qaxi/ciscosmb/
    - name: Sanity checks
      run: |
        cd ~/.ansible/collections/ansible_collections/qaxi/ciscosmb
        ansible-test sanity --python 3.8
    - name: Unit tests
      run: |
        cd ~/.ansible/collections/ansible_collections/qaxi/ciscosmb
        ansible-test units --python 3.8
    - name: Deploy to Galaxy
      run: |
        rm -f ./qaxi-ciscosmb-*.tar.gz 
        ansible-galaxy collection build -vvv --force
        export GALAXY_IMPORTER_CONFIG=./galaxy-importer.cfg
        python3 -m galaxy_importer.main qaxi-ciscosmb-*.tar.gz
        && ansible-galaxy collection publish -vvv \
            ./qaxi-ciscosmb-*.tar.gz --token ${{ secrets.GALAXY_TOKEN }}
        rm -f ./qaxi-ciscosmb-*.tar.gz 
