# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ansible tests - UB20.04 Py 3.8

on:
  push:
    branches-ignore: [ main ]

  pull_request:
    branches-ignore: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        #python-version: [ 3.6, 3.7, 3.8, 3.9 ]
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/unit/requirements.txt
        
        ansible-galaxy collection install ansible.netcommon
        mkdir -p ~/.ansible/collections/ansible_collections/community/ciscosmb
        cp -r * ~/.ansible/collections/ansible_collections/community/ciscosmb/
    - name: Sanity checks
      run: |
        cd ~/.ansible/collections/ansible_collections/community/ciscosmb
        ansible-test sanity --python ${{ matrix.python-version }}
    - name: Unit tests
      run: |
        cd ~/.ansible/collections/ansible_collections/community/ciscosmb
        ansible-test units --python ${{ matrix.python-version }}
    - name: Test deploy to Galaxy
      run: |
        rm -f ./community-ciscosmb-*.tar.gz 
        ansible-galaxy collection build -vvv --force
        export GALAXY_IMPORTER_CONFIG=./galaxy-importer.cfg
        python3 -m galaxy_importer.main community-ciscosmb-*.tar.gz
        rm -f ./community-ciscosmb-*.tar.gz
